apiVersion: v1
kind: Pod
metadata:
  name: access-node
spec:
  hostPID: true
  containers:
  - name: nsenter
    image: ubuntu
    command:
      - nsenter
      - --target=1
      - --mount
      - --uts
      - --ipc
      - --net
      - --pid
      - /bin/bash
    stdin: true
    tty: true
    securityContext:
      privileged: true
