apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s

    # Define remote write configuration if you want to send data to long-term storage
    remote_write:
      # Configure remote write options here, if needed

    