apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      kubeletstats:
        collection_interval: 10s
        auth_type: 'serviceAccount'
        endpoint: '${env:K8S_NODE_NAME}:10250'
        insecure_skip_verify: true
        metric_groups:
          - node
          - pod
          - container
      k8s_cluster:
        collection_interval: 10s
        auth_type: 'serviceAccount'
      filelog:
        include:
          - /var/log/containers/*.log              # Container logs
          - /var/log/pods/**/*.log                 # Pod logs
          - /var/log/syslog                        # Node logs (assuming Linux-based nodes)
          - /var/log/kubelet/kubelet.log           # Node logs (Kubelet)
          - /var/log/kubernetes/**/*.log           # Cluster logs (Kubernetes system logs)
          - /var/log/journal/node/*                # Node logs (systemd journal if applicable)
          - /var/log/kube-apiserver.log            # Cluster logs (API server)
          - /var/log/kube-scheduler.log            # Cluster logs (Scheduler)
          - /var/log/kube-controller-manager.log   # Cluster logs (Controller Manager)
          - /var/log/etcd.log                      # Cluster logs (etcd)
        start_at: beginning
        operators:
          - type: regex_parser
            regex: '^(?P<timestamp>[^ ]+) (?P<stream>stdout|stderr) (?P<log>.*)$'
            timestamp:
              parse_from: attributes.timestamp
              layout: '%Y-%m-%dT%H:%M:%S.%f%z'
          - type: regex_parser
            regex: '(?P<severity>(DEBUG|INFO|WARN|ERROR|FATAL))'
            parse_from: attributes.log
          - type: move
            from: attributes.log
            to: attributes.log_message
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kubelet'
              static_configs:
                - targets: ['${env:K8S_NODE_NAME}:10250']
            - job_name: 'kube-state-metrics'
              scrape_interval: 10s
              static_configs:
                - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
            - job_name: 'otel_collector'
              scrape_interval: 5s
              static_configs:
                - targets:
                    - collector:8889

    processors:
      batch:
        send_batch_max_size: 1000
        send_batch_size: 100
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 500
      k8sattributes:
        auth_type: 'serviceAccount'
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.uid

    exporters:
      debug:
        verbosity: detailed  

      # This defines a Prometheus remote write exporter. It sends metrics data to a Prometheus server.
      prometheusremotewrite:
        endpoint: "http://prometheus:9090/api/v1/write"  # Sets the endpoint of the Prometheus server
        resource_to_telemetry_conversion:
          enabled: true # Convert resource attributes to metric labels

      # This defines an exporter for Tempo backend. It sends trace data to a Tempo instance.
      otlp/tempo:
        endpoint: "http://tempo:4317"  # Sets the endpoint of the Tempo server

        # TLS configuration for the Tempo exporter
        tls:
          insecure: true  # Disables TLS certificate verification (not recommended for production)

      # This defines an exporter for Loki. It sends log data to a Loki server.
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"  # Sets the endpoint of the Loki server

    service:
      pipelines:
        metrics:
          receivers: [otlp, kubeletstats, prometheus, k8s_cluster]
          processors: [batch]
          exporters: [prometheusremotewrite, debug]
        traces:
          receivers: [otlp]
          processors: [batch, memory_limiter, k8sattributes]
          exporters: [otlp/tempo]
        logs:
          receivers: [otlp, filelog]
          processors: [batch, memory_limiter, k8sattributes]
          exporters: [loki, debug]
