apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        args:
          - "-config.file=/etc/tempo.yml"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tempo.yml
          subPath: tempo.yml
      volumes:
      - name: config-volume
        configMap:
          name: tempo-config
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: tempo-http
      protocol: TCP
      port: 3200
      targetPort: 3200
  type: ClusterIP
