apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
spec:
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      serviceAccountName: collector-sa  # Specify the ServiceAccount
      containers:
      - name: collector
        image: otel/opentelemetry-collector-contrib:0.91.0
        args: ["--config=/etc/otelcol-contrib/otel-collector.yml"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otelcol-contrib/otel-collector.yml
          subPath: otel-collector.yml
        - name: varlogpods
          mountPath: /var/log/pods
          readOnly: true
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-config
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  selector:
    app: collector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: otlp-grpc
    - protocol: TCP
      port: 8889
      targetPort: 8889
      name: prometheus
  type: ClusterIP
