apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-cr
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["nodes/proxy", "nodes/stats", "nodes/metrics", "nodes/spec", "nodes"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/stats/summary"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-cr
subjects:
  - kind: ServiceAccount
    name: collector-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: otel-collector-cr
  apiGroup: rbac.authorization.k8s.io
