apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics-sa
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics-full-cr
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics-full-crb
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-state-metrics-full-cr
  apiGroup: rbac.authorization.k8s.io
